### ISSUE TITLE
"AttributeError: can't set attribute" when running rationale_dependent.py 

### ISSUE THREAD

**Issue by rva5120** [RiaanZoetmulder/Master-Thesis#3]
Hello,

I'm getting the following error when running your code:

Traceback (most recent call last):
  File "rationale_dependent.py", line 88, in <module>
    main()
  File "rationale_dependent.py", line 63, in main
    model.ready()
  File "/Users/raquelalvarez/rcnn_tf/Master-Thesis/rationale/models.py", line 407, in ready
    self.generator.ready()
  File "/Users/raquelalvarez/rcnn_tf/Master-Thesis/rationale/models.py", line 118, in ready
    initializer = self.zero_states[0])
  File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 613, in scan
    back_prop=back_prop, swap_memory=swap_memory)
  File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 603, in compute
    a_out = fn(packed_a, packed_elems)
  File "/Users/raquelalvarez/rcnn_tf/Master-Thesis/rationale/advanced_layers.py", line 177, in __call__
    **self.name = "RCNN_cell" + '_%s'% (str(self._idx))
AttributeError: can't set attribute**

Since RNNCell inherits from Layer, and Layer's name attribute is a "Read-only property" (according to https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/python/layers/base.py), then maybe that's why it can't be updated? Were you able to run the code without this issue?

I'm running this on Tensorflow 1.5.0

**Comment by mglowacki100** [comment]
This error don't appears at Tensorflow 1.2, it works on CPU, but on GPU freeze without any error.
Btw. there is a pyTorch version.

**Comment by albertwy** [comment]
> Hello,
> 
> I'm getting the following error when running your code:
> 
> Traceback (most recent call last):
> File "rationale_dependent.py", line 88, in 
> main()
> File "rationale_dependent.py", line 63, in main
> model.ready()
> File "/Users/raquelalvarez/rcnn_tf/Master-Thesis/rationale/models.py", line 407, in ready
> self.generator.ready()
> File "/Users/raquelalvarez/rcnn_tf/Master-Thesis/rationale/models.py", line 118, in ready
> initializer = self.zero_states[0])
> File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 613, in scan
> back_prop=back_prop, swap_memory=swap_memory)
> File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2934, in while_loop
> result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
> File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2720, in BuildLoop
> pred, body, original_loop_vars, loop_vars, shape_invariants)
> File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2662, in _BuildLoop body_result = body(*packed_vars_for_body) File "/Users/raquelalvarez/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 603, in compute a_out = fn(packed_a, packed_elems) File "/Users/raquelalvarez/rcnn_tf/Master-Thesis/rationale/advanced_layers.py", line 177, in **call** **self.name = "RCNN_cell" + '_%s'% (str(self._idx))
> AttributeError: can't set attribute**
> 
> Since RNNCell inherits from Layer, and Layer's name attribute is a "Read-only property" (according to https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/python/layers/base.py), then maybe that's why it can't be updated? Were you able to run the code without this issue?
> 
> I'm running this on Tensorflow 1.5.0

Do you solve it? I got the same problem. But I don't know how to fix it.
